---

- name: Make Sure SSL Dir Exists ({{ ssl_dir }})
  file:
    path="{{ ssl_dir }}"
    owner="{{ ssl_unix_user }}"
    group="{{ ssl_unix_group }}"
    mode="0700"
    recurse="yes"
    state="directory"

- name: Dump SSL Certificates
  copy:
    content="{{ item.crt }}"
    dest="{{ ssl_dir }}/{{ item.endpoint }}.crt"
    owner="{{ ssl_unix_user }}"
    group="{{ ssl_unix_group }}"
    mode="0600"
    backup="yes"
  with_items: "{{ ssl_bundles }}"

- name: Dump SSL Private Keys
  copy:
    content="{{ item.key }}"
    dest="{{ ssl_dir }}/{{ item.endpoint }}.key"
    owner="{{ ssl_unix_user }}"
    group="{{ ssl_unix_group }}"
    mode="0600"
    backup="yes"
  with_items: "{{ ssl_bundles }}"
  no_log: true

- name: Dump SSL PEMs
  template:
    src="ssl.pem.j2"
    dest="{{ ssl_dir }}/{{ item.endpoint }}.pem"
    owner="{{ ssl_unix_user }}"
    group="{{ ssl_unix_group }}"
    mode="0600"
    backup="yes"
  with_items: "{{ ssl_bundles }}"
  no_log: true
